webserver:
  listen_addr: "0.0.0.0"
  listen_port: 8080
  full_url: "/full-stream"
  lite_url: "/lite"
  domains_only_url: "/domains-only"
  cert_path: ""
  cert_key_path: ""

prometheus:
  enabled: true
  listen_addr: "0.0.0.0"
  listen_port: 8080
  metrics_url: "/full-stream"