version: '3'
services:
  derekrgreene:
    build:
      context: .
    ports:
      - "8050:8050"
    env_file:
      - .env
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPW}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBPW}
      MYSQL_PASSWORD: ${DBPW} 
    ports:
      - "3306:3306" 
    volumes:
      - ./flask_proj/database/es_db.sql:/docker-entrypoint-initdb.d/es_db.sql
    restart: always

  engdb:
    build:
      context: ./flask_proj
    ports:
      - "8051:8051"
    env_file:
      - .env
    restart: always

volumes:
  db_data: