version: '3'
services:
  derekrgreene:
    build:
      context: .
    ports:
      - "8050:8050"
    env_file:
      - .env
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${340DBPW}
      MYSQL_DATABASE: ${340DB}
      MYSQL_USER: ${340DBPW}
      MYSQL_PASSWORD: ${340DBPW} 
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  engdb:
    build:
      context: ./flask_proj
    ports:
      - "8051:8051"
    env_file:
      - .env
    restart: always

volumes:
  db_data: