name: Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '28.0.1'

      - name: Install dependencies
        working-directory: ./derekrgreene
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run tests
        working-directory: ./derekrgreene
        run: |
          mix test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
      - name: Send deploy webhook
        run: |
          curl -X POST https://derekrgreene.com/deploy \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: push" \
          -H "X-Hub-Signature-256: sha256=$(echo -n '{"deployment": "true"}' | openssl dgst -sha256 -hmac "${{ secrets.BGITHUB_SECRET }}" | cut -d' ' -f2)" \
          -d '{"deployment": "true"}'
