name: Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_app.py --maxfail=1 --disable-warnings -q  

  deploy:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Send deploy webhook to Flask app
        if: success()  
        run: |
          curl -X POST https://derekrgreene.com/deploy \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=${{ secrets.WEBHOOK_SECRET }}" \
          -d '{"deployment": "true"}'
